- name: Deploy EC2 instance using Ansible Galaxy Role
  hosts: localhost
  gather_facts: no
  become: false  

  roles:
    - ec2-instance

#use this command to run the ansible-galaxy script
#ansible-playbook ec2_instance.yml -e "elastic_ip=13.202.211.207"