- name: Launch EC2 instance in existing VPC & Subnet
  amazon.aws.ec2_instance:
    name: "MyAnsibleInstance"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    security_groups:  
      - "{{ security_group_id }}"
    vpc_subnet_id: "{{ subnet_id }}"  
    image_id: "{{ ami_id }}"
    region: "{{ aws_region }}"
    count: 1
    wait: yes
    tags:
      Name: Ansible-EC2
  register: ec2

- name: Wait for EC2 instance to be in running state
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
    instance_ids: "{{ ec2.instances[0].instance_id }}"
  register: ec2_info
  until: ec2_info.instances[0].state.name == "running"
  retries: 10
  delay: 10

- name: Associate Elastic IP with EC2 instance
  amazon.aws.ec2_eip:
    region: "{{ aws_region }}"
    public_ip: "{{ elastic_ip }}"
    device_id: "{{ ec2.instances[0].network_interfaces[0].network_interface_id }}"
    in_vpc: true
  when: elastic_ip is defined
